version: "2"
checks:
  method-complexity:
    config:
      threshold: 7
plugins:
  rubocop:
    enabled: true
    channel: rubocop-1-9-1
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  scss-lint:
    enabled: true
  duplication:
    enabled: true
